### ISSUE TITLE
How to ensure each xdist process gets a different random seed reproducibly?

### ISSUE THREAD

**Issue by l0b0** [pytest-dev/pytest-randomly#327]
I'm working on a [project](https://github.com/linz/geospatial-data-lake) which uses [random generators](https://github.com/linz/geospatial-data-lake/blob/ec7ef27c99ccfdd72e09883fb70e23c1ccff5bc6/tests/general_generators.py) to make sure tests which generate things like [database entries](https://github.com/linz/geospatial-data-lake/blob/master/tests/test_dataset_versions_endpoint.py) don't create duplicates. I've combined this with pytest-randomly and `"--randomly-seed=${GITHUB_RUN_ID}" --randomly-dont-reset-seed` to have *reproducible* randomness: if the CI pipeline fails I can easily re-run the exact same thing locally. This is working fine, but when combined with pytest-xdist it looks like each worker is getting the same *initial* seed, and so the tests are back to generating duplicate values.

Is there some way to send a reproducible but *different* seed to each test when combined with python-xdist?

**Comment by adamchainz** [comment]
pytest-randomly goes out of its way to ensure each process gets the same seed, otherwise tests won't be reproducible. The splitting between workers is non-deterministic since it relies on test runtime, which is noisy.

If you need to ensure different database records are created from different processes, you can use `os.getpid()` for a different number in each process. This could be used in a hash or as a seed to a local `Random()` instance (which pytest-randomly won't affect)
